main: dev.deltamc.deltalib.DeltaLib
name: DeltaLib
version: '${project.version}'
description: The main Lib class for all the Delta Plugins
author: Akila
softdepend:
  - PlaceholderAPI
  - EnderTranslate
depend:
  - Vault